### ISSUE TITLE
what should i do when it happened?

### ISSUE THREAD

**Issue by javatoai** [simple-robot/simbot-mirai-login-solver-selenium-helperPack#1]
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: love.forte.simbot.bot.BotVerifyException: Cannot verifier bot code: 1677688026
        at love.forte.simbot.component.mirai.configuration.MiraiBotVerifier.verity(MiraiBotVerifier.kt:117)
        at love.forte.simbot.component.mirai.configuration.MiraiBotManager.registerBot(MiraiBotManager.kt:100)
        at love.forte.smlssh.App.main(App.java:79)
        ... 8 more
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1677688026), code=237, title=禁止登录, message=当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。, errorInfo=), tips=若频繁出现, 请尝试开启设备锁
        at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler.doSlowLogin(QQAndroidBotNetworkHandler.kt:335)
        at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler$doSlowLogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at love.forte.simbot.component.mirai.configuration.MiraiBotVerifier.verity(MiraiBotVerifier.kt:86)
        ... 10 more

**Comment by ForteScarlet** [comment]
首先，如果你有足够多可以进行尝试的账号，最快捷的办法是多换个账号试试

这个问题是因为tx觉得你账号或网络异常，所以目前暂时没有什么绝对性的解决方案。

你可以尝试：
1. 更换账号并使用滑块验证工具
2. 开启或者关闭设备锁，各种情况都试试
3. 换一个网络环境，例如切换为热点
4. 用电脑或者手机多挂挂你要用的账号，养养号后再尝试
5. 以上方法都进行多次尝试 
6. 以上方法都不一定成功，但是目前来看，一段时间内基本上就会变正常
