### ISSUE TITLE
How do this happened?

### ISSUE THREAD

**Issue by kxx6666** [simple-robot/simbot-mirai-login-solver-selenium-helperPack#2]
Tips: 你知道吗？catCode开发团队的成员们都很喜欢猫。

20:01:07.976 [main] INFO love.forte.smlssh.App - Active resources: [simbot.properties, simbot.yml]
20:01:08.047 [main] DEBUG love.forte.smlssh.App - resource [simbot.yml] loaded.
20:01:08.225 [main] DEBUG love.forte.smlssh.App - load auto configure resource: jar:file:/D:/学习/bot/simbot-mirai-login-solver-selenium-helper.jar!/BOOT-INF/lib/component-mirai-2.0.8.jar!/META-INF/simbot.factories
20:01:08.253 [main] DEBUG love.forte.smlssh.App - load auto configure resource: jar:file:/D:/学习/bot/simbot-mirai-login-solver-selenium-helper.jar!/BOOT-INF/lib/client-core-2.0.8.jar!/META-INF/simbot.factories
20:01:08.258 [main] DEBUG love.forte.smlssh.App - load auto configure resource: jar:file:/D:/学习/bot/simbot-mirai-login-solver-selenium-helper.jar!/BOOT-INF/lib/client-ktor-2.0.8.jar!/META-INF/simbot.factories
20:01:08.262 [main] DEBUG love.forte.smlssh.App - load auto configure resource: jar:file:/D:/学习/bot/simbot-mirai-login-solver-selenium-helper.jar!/BOOT-INF/lib/json-fastjson-2.0.8.jar!/META-INF/simbot.factories
20:01:08.267 [main] DEBUG love.forte.smlssh.App - load auto configure resource: jar:file:/D:/学习/bot/simbot-mirai-login-solver-selenium-helper.jar!/BOOT-INF/lib/core-2.0.8.jar!/META-INF/simbot.factories
20:01:08.308 [main] DEBUG love.forte.smlssh.App - load auto configure resource: jar:file:/D:/学习/bot/simbot-mirai-login-solver-selenium-helper.jar!/BOOT-INF/lib/component-mirai-2.0.8.jar!/META-INF/simbot.factories
20:01:08.309 [main] DEBUG love.forte.smlssh.App - load auto configure resource: jar:file:/D:/学习/bot/simbot-mirai-login-solver-selenium-helper.jar!/BOOT-INF/lib/client-core-2.0.8.jar!/META-INF/simbot.factories
20:01:08.310 [main] DEBUG love.forte.smlssh.App - load auto configure resource: jar:file:/D:/学习/bot/simbot-mirai-login-solver-selenium-helper.jar!/BOOT-INF/lib/client-ktor-2.0.8.jar!/META-INF/simbot.factories
20:01:08.310 [main] DEBUG love.forte.smlssh.App - load auto configure resource: jar:file:/D:/学习/bot/simbot-mirai-login-solver-selenium-helper.jar!/BOOT-INF/lib/json-fastjson-2.0.8.jar!/META-INF/simbot.factories
20:01:08.310 [main] DEBUG love.forte.smlssh.App - load auto configure resource: jar:file:/D:/学习/bot/simbot-mirai-login-solver-selenium-helper.jar!/BOOT-INF/lib/core-2.0.8.jar!/META-INF/simbot.factories
20:01:09.457 [main] DEBUG love.forte.smlssh.App - package scan: love.forte.smlssh
20:01:09.635 [main] INFO love.forte.simbot.component.mirai.configuration.MiraiEventCacheConfiguration - Disable default mirai message cache.
[92m2021-06-12 20:01:09 I/Mirai: Mirai 正在使用桌面环境. 如遇到验证码将会弹出对话框. 可添加 JVM 属性 `mirai.no-desktop` 以关闭.[0m
[92m2021-06-12 20:01:09 I/Mirai: Mirai is using desktop. Captcha will be thrown by window popup. You can add `mirai.no-desktop` to JVM properties (-Dmirai.no-desktop) to disable it.[0m
Line:     ProgId    REG_SZ    ChromeHTML.QTAYPWCUQDOAP5BGVGHTP25AS4, b64:ICAgIFByb2dJZCAgICBSRUdfU1ogICAgQ2hyb21lSFRNTC5RVEFZUFdDVVFET0FQNUJHVkdIVFAyNUFTNA==
List: [, ProgId, REG_SZ, ChromeHTML.QTAYPWCUQDOAP5BGVGHTP25AS4]
Line:     name    REG_SZ    Google Chrome, b64:ICAgIG5hbWUgICAgUkVHX1NaICAgIEdvb2dsZSBDaHJvbWU=
List: [, name, REG_SZ, Google Chrome]
Line:     pv    REG_SZ    91.0.4472.101, b64:ICAgIHB2ICAgIFJFR19TWiAgICA5MS4wLjQ0NzIuMTAx
List: [, pv, REG_SZ, 91.0.4472.101]
[2021-06-12 20:01:10 MxLib Selenium - Chrome] Running on 中国-大陆
[2021-06-12 20:01:10 MxLib Selenium - Chrome] Using taoboo mirror default
[2021-06-12 20:01:10 MxLib Selenium - Chrome] MxLib will download chrome driver from http://npm.taobao.org/mirrors/chromedriver/
[2021-06-12 20:01:10 MxLib Selenium - Chrome] Change it with `-Dmxlib.selenium.chrome.mirror=.....` vm option
[2021-06-12 20:01:10 MxLib Selenium - Chrome] Or disable it with `-Dmxlib.selenium.chrome.no-mirror`
Downloading chromedriver-91.0.4472.101.exe from http://npm.taobao.org/mirrors/chromedriver/91.0.4472.101/chromedriver_win32.zip
[91m2021-06-12 20:01:10 W/Mirai: Error in loading mirai-login-solver-selenium, skip
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.mamoe.mirai.internal.utils.SeleniumLoginSolverSupportKt$SeleniumLoginSolver$2.invoke(SeleniumLoginSolverSupport.kt:19)
        at net.mamoe.mirai.internal.utils.SeleniumLoginSolverSupportKt$SeleniumLoginSolver$2.invoke(SeleniumLoginSolverSupport.kt)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at net.mamoe.mirai.internal.utils.SeleniumLoginSolverSupportKt.getSeleniumLoginSolver(SeleniumLoginSolverSupport.kt)
        at net.mamoe.mirai.internal.utils.SeleniumLoginSolverSupportKt$isSliderCaptchaSupportKind$2.invoke(SeleniumLoginSolverSupport.kt:35)
        at net.mamoe.mirai.internal.utils.SeleniumLoginSolverSupportKt$isSliderCaptchaSupportKind$2.invoke(SeleniumLoginSolverSupport.kt)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at net.mamoe.mirai.internal.utils.SeleniumLoginSolverSupportKt.isSliderCaptchaSupportKind(SeleniumLoginSolverSupport.kt)
        at net.mamoe.mirai.utils.LoginSolver.<clinit>(LoginSolver.jvm.kt:101)
        at net.mamoe.mirai.utils.BotConfiguration.<init>(BotConfiguration.kt:224)
        at net.mamoe.mirai.utils.BotConfiguration.<clinit>(BotConfiguration.kt:587)
        at love.forte.simbot.component.mirai.configuration.MiraiConfiguration.<init>(MiraiConfiguration.kt:61)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at love.forte.common.ioc.DependCenter$constrInstance$2.invoke(DependCenter.kt:450)
        at love.forte.common.ioc.DependCenter$constrInstance$2.invoke(DependCenter.kt:56)
        at love.forte.common.ioc.DependCenter$inject0$realInstanceSupplier$1.invoke(DependCenter.kt:264)
        at love.forte.common.ioc.DependCenter$inject0$realInstanceSupplier$1.invoke(DependCenter.kt:263)
        at love.forte.common.ioc.DependCenter$inject0$instanceSupplier$1.invoke(DependCenter.kt:279)
        at love.forte.common.ioc.DependCenter$inject0$instanceSupplier$1.invoke(DependCenter.kt:271)
        at love.forte.common.ioc.DependCenter$inject0$instanceSupplierWithConfig$1.invoke(DependCenter.kt:291)
        at love.forte.common.ioc.DependCenter$inject0$instanceSupplierWithConfig$1.invoke(DependCenter.kt:290)
        at love.forte.common.ioc.DependCenter.getOrThrow(DependCenter.kt:1032)
        at love.forte.common.ioc.DependCenter$childMethodToEmptyInstanceSupplier$$inlined$mapIndexed$lambda$1.invoke(DependCenter.kt:530)
        at love.forte.common.ioc.DependCenter$childMethodToEmptyInstanceSupplier$$inlined$mapIndexed$lambda$1.invoke(DependCenter.kt:56)
        at love.forte.common.ioc.DependCenter$childMethodToEmptyInstanceSupplier$1.invoke(DependCenter.kt:601)
        at love.forte.common.ioc.DependCenter$childMethodToEmptyInstanceSupplier$1.invoke(DependCenter.kt:56)
        at love.forte.common.ioc.DependCenter$injectChildren$3$realInstanceSupplier$1.invoke(DependCenter.kt:362)
        at love.forte.common.ioc.DependCenter$injectChildren$3$realInstanceSupplier$1.invoke(DependCenter.kt:361)
        at love.forte.common.ioc.DependCenter$injectChildren$3$instanceSupplier$1.invoke(DependCenter.kt:374)
        at love.forte.common.ioc.DependCenter$injectChildren$3$instanceSupplier$1.invoke(DependCenter.kt:369)
        at love.forte.common.ioc.DependCenter.getOrThrow(DependCenter.kt:1032)
        at love.forte.common.ioc.DependCenter$constrInstance$$inlined$mapIndexed$lambda$4.invoke(DependCenter.kt:442)
        at love.forte.common.ioc.DependCenter$constrInstance$$inlined$mapIndexed$lambda$4.invoke(DependCenter.kt:56)
        at love.forte.common.ioc.DependCenter$constrInstance$1.invoke(DependCenter.kt:447)
        at love.forte.common.ioc.DependCenter$constrInstance$1.invoke(DependCenter.kt:56)
        at love.forte.common.ioc.DependCenter$inject0$realInstanceSupplier$1.invoke(DependCenter.kt:264)
        at love.forte.common.ioc.DependCenter$inject0$realInstanceSupplier$1.invoke(DependCenter.kt:263)
        at love.forte.common.ioc.DependCenter$inject0$instanceSupplier$1.invoke(DependCenter.kt:279)
        at love.forte.common.ioc.DependCenter$inject0$instanceSupplier$1.invoke(DependCenter.kt:271)
        at love.forte.common.ioc.DependCenter.getOrThrow(DependCenter.kt:1032)
        at love.forte.common.ioc.DependCenter$constrInstance$$inlined$mapIndexed$lambda$4.invoke(DependCenter.kt:442)
        at love.forte.common.ioc.DependCenter$constrInstance$$inlined$mapIndexed$lambda$4.invoke(DependCenter.kt:56)
        at love.forte.common.ioc.DependCenter$constrInstance$1.invoke(DependCenter.kt:447)
        at love.forte.common.ioc.DependCenter$constrInstance$1.invoke(DependCenter.kt:56)
        at love.forte.common.ioc.DependCenter$inject0$realInstanceSupplier$1.invoke(DependCenter.kt:264)
        at love.forte.common.ioc.DependCenter$inject0$realInstanceSupplier$1.invoke(DependCenter.kt:263)
        at love.forte.common.ioc.DependCenter$inject0$instanceSupplier$1.invoke(DependCenter.kt:279)
        at love.forte.common.ioc.DependCenter$inject0$instanceSupplier$1.invoke(DependCenter.kt:271)
        at love.forte.common.ioc.DependCenter.getOrThrow(DependCenter.kt:1032)
        at love.forte.common.ioc.DependCenter$instanceInjectFunc$$inlined$map$lambda$1.invoke(DependCenter.kt:663)
        at love.forte.common.ioc.DependCenter$instanceInjectFunc$$inlined$map$lambda$1.invoke(DependCenter.kt:56)
        at love.forte.common.ioc.DependCenter$instanceInjectFunc$funcs$1$3.invoke(DependCenter.kt:735)
        at love.forte.common.ioc.DependCenter$instanceInjectFunc$funcs$1$3.invoke(DependCenter.kt:56)
        at love.forte.common.ioc.DependCenter$instanceInjectFunc$2.invoke(DependCenter.kt:743)
        at love.forte.common.ioc.DependCenter$instanceInjectFunc$2.invoke(DependCenter.kt:56)
        at love.forte.common.ioc.DependCenter$inject0$realInstanceSupplier$1.invoke(DependCenter.kt:265)
        at love.forte.common.ioc.DependCenter$inject0$realInstanceSupplier$1.invoke(DependCenter.kt:263)
        at love.forte.common.ioc.DependCenter$inject0$instanceSupplier$1.invoke(DependCenter.kt:279)
        at love.forte.common.ioc.DependCenter$inject0$instanceSupplier$1.invoke(DependCenter.kt:271)
        at love.forte.common.ioc.DependCenter.init(DependCenter.kt:102)
        at love.forte.simbot.core.SimbotApp.initDependCenter(SimbotApp.kt:396)
        at love.forte.simbot.core.SimbotApp.run$core(SimbotApp.kt:241)
        at love.forte.simbot.core.SimbotApp$Run.run(SimbotApp.kt:465)
        at love.forte.simbot.core.SimbotApp$Run.run$default(SimbotApp.kt:428)
        at love.forte.simbot.core.SimbotApp$Run.run(SimbotApp.kt)
        at love.forte.simbot.core.SimbotApp.run(SimbotApp.kt)
        at love.forte.smlssh.App.main(App.java:73)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.RuntimeException: Exception in loading selenium
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl.<init>(SeleniumLoginSolverImpl.kt:32)
        at net.mamoe.mirai.selenium.SeleniumLoginSolver$SeleniumLoginSolver$2.invoke(SeleniumLoginSolver.kt:17)
        at net.mamoe.mirai.selenium.SeleniumLoginSolver$SeleniumLoginSolver$2.invoke(SeleniumLoginSolver.kt)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at net.mamoe.mirai.selenium.SeleniumLoginSolver.getInstance(SeleniumLoginSolver.kt)
        ... 82 more
Caused by: java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at io.github.karlatemp.mxlib.selenium.MxSelenium.lambda$initialize0$2(MxSelenium.java:203)
        at io.github.karlatemp.mxlib.selenium.NetKit.download(NetKit.java:67)
        at io.github.karlatemp.mxlib.selenium.NetKit.download(NetKit.java:34)
        at io.github.karlatemp.mxlib.selenium.MxSelenium.initialize0(MxSelenium.java:198)
        at io.github.karlatemp.mxlib.selenium.MxSelenium.initialize(MxSelenium.java:138)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt$setup$2.invoke(SeleniumLoginSolverImpl.kt:63)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt$setup$2.invoke(SeleniumLoginSolverImpl.kt)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt.getSetup(SeleniumLoginSolverImpl.kt)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl.<init>(SeleniumLoginSolverImpl.kt:31)
        ... 86 more
[0m
20:01:10.555 [main] WARN love.forte.simbot.core.configuration.CoreBotRegistrar - No bot information is configured.
20:01:10.555 [main] DEBUG love.forte.simbot.core.configuration.CoreListenerRegistrar - Start register listeners.
20:01:10.557 [main] DEBUG love.forte.simbot.core.configuration.CoreListenerRegistrar - Starter register listeners by love.forte.simbot.core.configuration.CoreMethodPostListenerRegistrar@612fc6eb.
20:01:10.557 [main] INFO love.forte.simbot.core.configuration.CoreMethodPostListenerRegistrar - Ready to register method listeners.
20:01:10.557 [main] DEBUG love.forte.simbot.core.configuration.CoreMethodPostListenerRegistrar - Number of beans to be scanned: 79
20:01:10.606 [main] INFO love.forte.simbot.core.configuration.CoreMethodPostListenerRegistrar - Method listeners Registration is complete.
20:01:10.606 [main] DEBUG love.forte.simbot.core.configuration.CoreListenerRegistrar - Listeners registered.
20:01:10.609 [main] DEBUG love.forte.simbot.core.configuration.CoreListenerRegistrar - Do registered by love.forte.simbot.component.mirai.configuration.MiraiListenerRegistered@2a70a3d8.
20:01:10.610 [main] WARN love.forte.simbot.core.configuration.CoreListenerRegistrar - Registration Bots is empty.
20:01:10.613 [main] DEBUG love.forte.simbot.component.mirai.configuration.MiraiBotManager - Verify Bot 1942377467.
20:01:10.613 [main] DEBUG love.forte.simbot.component.mirai.configuration.MiraiBotVerifier - verify bot code: 1942377467
20:01:11.087 [main] INFO love.forte.simbot.component.mirai.configuration.MiraiConfiguration - DevInfo write to D:\学习\bot\simbot-devInfo.json
20:01:11.464 [main] INFO love.forte.simbot.component.mirai.bot.1942377467 - Logging in...
20:01:11.851 [main] INFO love.forte.simbot.component.mirai.net.1942377467 - Connected to server 203.205.255.224:8080
20:01:11.852 [main] INFO love.forte.simbot.component.mirai.configuration.MiraiConfiguration - DevInfo write to D:\学习\bot\simbot-devInfo.json
20:01:12.845 [main] INFO love.forte.simbot.component.mirai.net.1942377467 - Connected to server 203.205.255.224:8080
20:01:12.846 [main] INFO love.forte.simbot.component.mirai.configuration.MiraiConfiguration - DevInfo write to D:\学习\bot\simbot-devInfo.json
20:01:13.281 [main] ERROR love.forte.simbot.component.mirai.configuration.MiraiBotVerifier - Verifier bot(1942377467) failed.
20:01:13.282 [main] INFO love.forte.simbot.component.mirai.bot.1942377467 - Bot cancelled: Bot closed
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: love.forte.simbot.bot.BotVerifyException: Cannot verifier bot code: 1942377467
        at love.forte.simbot.component.mirai.configuration.MiraiBotVerifier.verity(MiraiBotVerifier.kt:117)
        at love.forte.simbot.component.mirai.configuration.MiraiBotManager.registerBot(MiraiBotManager.kt:100)
        at love.forte.smlssh.App.main(App.java:79)
        ... 8 more
Caused by: net.mamoe.mirai.network.UnsupportedSliderCaptchaException: Mirai 无法完成滑块验证. 使用协议 ANDROID_PHONE 强 制要求滑块验证, 请更换协议后重试. 另请参阅: https://github.com/project-mirai/mirai-login-solver-selenium
        at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler.doSlowLogin(QQAndroidBotNetworkHandler.kt:300)
        at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler$doSlowLogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at love.forte.simbot.component.mirai.configuration.MiraiBotVerifier.verity(MiraiBotVerifier.kt:86)
        ... 10 more

**Comment by ForteScarlet** [comment]
从滑块工具的 [releases](https://github.com/simple-robot/simbot-mirai-login-solver-selenium-helperPack/releases) 下载编译好的jar包，在windows10桌面环境通过命令行 `java -jar xxxxx.jar` 执行并进行一次登录。

其中需要注意，设置 **chrome** 浏览器为你的windows默认浏览器。

**Comment by ForteScarlet** [comment]
测试后发现之前的验证方式已经不再可行，因此目前这个工具失效了。
你可以去参考一下：
https://github.com/project-mirai/mirai-login-solver-selenium

https://github.com/simple-robot/TxCaptchaHelper
